version: 2.1
orbs:
  orb-tools: circleci/orb-tools@10.1.0
jobs:
  test:
    parameters:
      image:
        type: string
    docker:
      - image: <<parameters.image>>:latest
    steps: 
      - checkout
workflows:
  publish-dev:
    jobs:
      - orb-tools/pack:
          source-dir: src/main
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
      - orb-tools/publish-dev:
         # context: Publishing Orb
          orb-name: elateral/sonarqube-scanner
          requires: [orb-tools/pack]
      - orb-tools/publish:
          orb-ref: elateral/sonarqube-scanner@1.0.0
          attach-workspace: true
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              only: master



