version: 2.1
orbs:
  orb-tools: circleci/orb-tools@10
workflows:
  publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          source-dir: src/main
      - orb-tools/publish-dev:
          context: Publishing Orb
          orb-name: sonarsource/sonarcloud
          orb-path: orb.yml
          requires:
            - orb-tools/lint
